package com.myspace.pamformmodeller;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Age of Car in Years")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Price of car in whole dollars")
	private java.lang.Integer price;
	@org.kie.api.definition.type.Label(value = "Type")
	private java.lang.String type;

	public Car() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public Car(java.lang.Integer age, java.lang.Integer price,
			java.lang.String type) {
		this.age = age;
		this.price = price;
		this.type = type;
	}

}